### ISSUE TITLE
GitHub API

### ISSUE THREAD

**Issue by MasterOfTheTiger** [Graviton-Code-Editor/updates#1]
Hey there! I do the same thing for my Electron app (fetch information about versions from a GitHub repo), but I recently discovered that this is unnecessary and can get a little messy. Instead, the GitHub API would make checking for updates easier because you can make a release without having to update this repo. The docs are here: https://developer.github.com/v3/repos/releases/#get-the-latest-release

**Comment by marc2332** [comment]
Whoah!! Thanks! I will take a look!

**Comment by MasterOfTheTiger** [comment]
Was this resolved? Are you using the GitHub API, or did you decide to proceed with your current system?

**Comment by marc2332** [comment]
Yes! I am using the Github API , see : https://github.com/Graviton-Code-Editor/Graviton-App/blob/master/src/javascript/updater.js

Thank you 💯
